import { useQuery } from "@tanstack/react-query";
import { Link, useParams } from "react-router-dom";
import { api } from "../api/client";
import { riskColor } from "../components/common";

export function InsightDetailPage() {
  const { groupId } = useParams<{ groupId: string }>();

  const { data, isLoading, error } = useQuery({
    queryKey: ["insight", groupId],
    queryFn: () => api.insight(groupId!),
    enabled: !!groupId,
  });

  if (isLoading) return <p className="text-slate-400">Loading insight...</p>;
  if (error || !data) return <p className="text-red-400">Insight report not found</p>;

  return (
    <div className="space-y-6">
      <Link to="/insights" className="text-sm text-cyan-400 hover:underline">← Back to insights</Link>

      <div className="flex flex-wrap items-center gap-3">
        <h2 className="text-xl font-semibold">Incident Analysis</h2>
        <span className={`rounded border px-2 py-0.5 text-xs uppercase ${riskColor(data.risk_level)}`}>
          {data.risk_level}
        </span>
        <span className="rounded bg-slate-800 px-2 py-0.5 text-xs text-slate-400">Generated by: {data.generated_by}</span>
      </div>

      <div className="rounded-lg border border-slate-800 bg-slate-900 p-4">
        <h3 className="text-sm font-medium text-slate-300">Summary</h3>
        <p className="mt-2 text-sm text-slate-200">{data.summary}</p>
      </div>

      <div className="grid gap-4 lg:grid-cols-2">
        <Section title="Root-Cause Hypotheses" items={data.root_cause_hypotheses} />
        <Section title="Recommendations" items={data.recommendations} />
      </div>

      <Section title="Remediation Steps" items={data.remediation_steps} />

      {data.operational_signals && (
        <div className="rounded-lg border border-slate-800 bg-slate-950 p-4">
          <h3 className="text-sm font-medium text-slate-300">Operational Signals</h3>
          <pre className="mt-2 overflow-x-auto text-xs text-slate-400">{JSON.stringify(data.operational_signals, null, 2)}</pre>
        </div>
      )}
    </div>
  );
}

function Section({ title, items }: { title: string; items: string[] }) {
  return (
    <div className="rounded-lg border border-slate-800 bg-slate-900 p-4">
      <h3 className="text-sm font-medium text-slate-300">{title}</h3>
      <ul className="mt-3 list-inside list-disc space-y-2 text-sm text-slate-300">
        {items.map((item, i) => (
          <li key={i}>{item}</li>
        ))}
      </ul>
    </div>
  );
}
